---
- name: Configure cron service
  service:
    name: "{{ cron_daemon_name }}"
    enabled: "{{ cron_service_enabled }}"
    state: "{{ cron_service_state }}"

- name: Configure cron variables
  cronvar:
    backup: "{{ item.backup | default(omit) }}"
    cron_file: "{{ item.cron_file | default(omit) }}"
    insertafter: "{{ item.insertafter | default(omit) }}"
    insertbefore: "{{ item.insertbefore | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    user: "{{ item.user | default(omit) }}"
    value: "{{ item.value | default(omit) }}"
  loop: "{{ cron_vars }}"
  notify: restart cron

- name: Configure cron jobs
  cron:
    backup: "{{ cron_crontab_backup | default(omit) }}"
    cron_file: "{{ item.cron_file | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    disabled: "{{ item.disabled | default(omit) }}"
    env: "{{ item.env | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    job: "{{ item.job | default(omit) }}"
    minute: "{{ item.minute | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    name: "{{ item.name | default(item) }}"
    special_time: "{{ item.special_time | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    user: "{{ item.user | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
  loop: "{{ cron_jobs }}"
  notify: restart cron
