---
- name: Install cron (RedHat)
  yum:
    name: "{{ cron_packages }}"
    state: present
    enablerepo: "{{ cron_enable_repo }}"
  when: ansible_os_family == "RedHat"

- name: Install cron (Debian)
  apt:
    name: "{{ cron_packages }}"
    state: present
  when: ansible_os_family == "Debian"
