---
- name: Include os family specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Set cron packages
  set_fact:
    cron_packages: "{{ __cron_packages }}"
  when: cron_packages | length == 0
