---
- name: Converge
  hosts: all
  vars:
    cron_vars:
      - name: PATH
        value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        user: root

      - name: SHELL
        value: /usr/bin/sh
        user: root

      - name: SHELL
        value: /usr/bin/zsh
        user: john.doe

    cron_jobs:
      - name: a_job
        user: root
        job: touch /tmp/a_job
        minute: '*/3'
        hour: '*'
        day: '*'
        month: '*'
        weekday: '*'

      - name: another_job
        user: application
        job: touch /tmp/another_job
        disabled: true
        minute: 40
        hour: '*'
        day: '*'
        month: '*'
        weekday: 3

      - name: and_another_job
        user: john.doe
        job: touch /tmp/and_another_job
        special_time: monthly

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
